In [1]:
a=[1,2,3]
b=[1,2,3]
c=a+b
print(c)

[1, 2, 3, 1, 2, 3]


In [7]:
import numpy as np
a=np.array([1,2,3])
b=np.array([1,2,3])
c=a
print(type(a))

<class 'numpy.ndarray'>


In [14]:
a=np.random.randint(1,4,size=(2,3,2,5))
print(a)
print(type(a))
print(a.ndim)

[[[[1 2 3 2 3]
   [1 3 2 2 1]]

  [[1 2 1 1 1]
   [2 1 1 1 2]]

  [[2 3 3 2 3]
   [2 1 2 1 1]]]


 [[[2 3 3 1 3]
   [1 2 1 1 2]]

  [[2 3 2 3 2]
   [1 2 1 3 1]]

  [[3 1 3 3 2]
   [2 3 3 3 3]]]]
<class 'numpy.ndarray'>
4


In [17]:
a=np.arange(1,5,0.5,dtype=np.float16)
print(a)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [25]:
a=np.linspace(0,5,num=10,endpoint=False,dtype=np.float16)
print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [26]:
a.itemsize

2

In [39]:
import pandas as pd
q=pd.DataFrame(a,index=np.arange(1,11))
print(q)

      0
1   0.0
2   0.5
3   1.0
4   1.5
5   2.0
6   2.5
7   3.0
8   3.5
9   4.0
10  4.5


In [40]:
q[0][1]

0.0

In [41]:
dict = {'A': 101,
		'B': 202,
		'C': 303}

In [49]:
d=pd.DataFrame(dict.values(),index=dict.keys(),columns=['no'])
print(d)

    no
A  101
B  202
C  303


In [51]:
d['no'][1]

202

In [53]:
d['no']['A']

101