In [1]:
a=[1,2,3]
b=[1,2,3]
c=a+b
print(c)

[1, 2, 3, 1, 2, 3]


In [7]:
import numpy as np
a=np.array([1,2,3])
b=np.array([1,2,3])
c=a
print(type(a))

<class 'numpy.ndarray'>


In [14]:
a=np.random.randint(1,4,size=(2,3,2,5))
print(a)
print(type(a))
print(a.ndim)

[[[[1 2 3 2 3]
   [1 3 2 2 1]]

  [[1 2 1 1 1]
   [2 1 1 1 2]]

  [[2 3 3 2 3]
   [2 1 2 1 1]]]


 [[[2 3 3 1 3]
   [1 2 1 1 2]]

  [[2 3 2 3 2]
   [1 2 1 3 1]]

  [[3 1 3 3 2]
   [2 3 3 3 3]]]]
<class 'numpy.ndarray'>
4


In [17]:
a=np.arange(1,5,0.5,dtype=np.float16)
print(a)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [25]:
a=np.linspace(0,5,num=10,endpoint=False,dtype=np.float16)
print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [26]:
a.itemsize

2